### ISSUE TITLE
Icon Issues

### ISSUE THREAD

**Issue by Citium-sys** [jdfossapps/shop-with-mom#3]
Having some issues with the icon. I have some strange flashing issues and uniformity issues. Is the icon adaptive? Currently on Android 10

**Comment by jdfossapps** [comment]
Thanks for reporting this. It's adaptative :S Can you reproduce the error in an online service like https://appetize.io/ ?

**Comment by Citium-sys** [comment]
I wasn't able to reproduce it. Could be a strange conflict with my phones OS. I'm running android 10 on MIUI. Here are some examples of the visual issues I'm having. (Haven't had any similar issues with other f-droid apps by the way.)

![IMG_20210210_140718](https://user-images.githubusercontent.com/65607010/107502317-92b65500-6ba9-11eb-95b8-82e6bb707289.jpg)

![Screenshot_2021-02-10-13-57-24-519_org jdfossapps android shopwithmom](https://user-images.githubusercontent.com/65607010/107502420-aeb9f680-6ba9-11eb-8fb3-a119e8744b96.jpg)

![IMG_20210210_140647](https://user-images.githubusercontent.com/65607010/107502522-cdb88880-6ba9-11eb-9a5d-90dfe09141b0.jpg)

**Comment by jdfossapps** [comment]
Hi @Citium-sys I just released a new version(v0.0.3) that hopefully fixes the icon issues. It should be available on F-droid in a few days.
![2021-03-02 11-33-40 High Res Screenshot](https://user-images.githubusercontent.com/74069719/109689886-61e39300-7b4b-11eb-939f-54a85d39ab5c.png)
Let me know if the fix works for you.

**Comment by jdfossapps** [comment]
I'm closing this issue as the fix is now live on f-droid. Feel free to open a new one if the issue persist
